---
namespace: deepthought_solutions
name: ansible_architect
version: 0.1.0
readme: README.md
authors:
  - Nicolas Karageuzian <nico@ds.local>
description: Ansible tools for an infrastructure architect
license:
  - GPL-3.0-or-later
license_file: LICENSE
tags:
  - structurizr
  - documentation
  - inventory
  - architecture
dependencies: {}
repository: https://github.com/deepthought-solutions/ansible-architect
documentation: https://github.com/deepthought-solutions/ansible-architect
homepage: https://github.com/deepthought-solutions/ansible-architect
issues: https://github.com/deepthought-solutions/ansible-architect/issues
build_ignore:
  - .git
  - .gitignore
  - .pre-commit-config.yaml
  - molecule
  - tests
  - "*.tar.gz"
